apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - name: pv-volume
      mountPath: /mnt
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
      claimName: postgres-pvc